// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzcmlfBVQSIdYIxlThhVO3T6Ua97Yq7Mc',
    appId: '1:30865018061:web:c22d749fb216807b44ad84',
    messagingSenderId: '30865018061',
    projectId: 'liveleak-a5d85',
    authDomain: 'liveleak-a5d85.firebaseapp.com',
    storageBucket: 'liveleak-a5d85.appspot.com',
    measurementId: 'G-LCTZWWGN3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyRQjFp6BJVHi6qC8Gcgn6U3Fs2VG42is',
    appId: '1:30865018061:android:1c4322d04ec1651644ad84',
    messagingSenderId: '30865018061',
    projectId: 'liveleak-a5d85',
    storageBucket: 'liveleak-a5d85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE8edHk8uUQ6UDs29Hclh31894DKON8sc',
    appId: '1:30865018061:ios:7c8cae73fa0e36d644ad84',
    messagingSenderId: '30865018061',
    projectId: 'liveleak-a5d85',
    storageBucket: 'liveleak-a5d85.appspot.com',
    iosClientId: '30865018061-ene2o9bmfbhr9usgeo67js3poehnn976.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveleak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE8edHk8uUQ6UDs29Hclh31894DKON8sc',
    appId: '1:30865018061:ios:c90290664b6b7ded44ad84',
    messagingSenderId: '30865018061',
    projectId: 'liveleak-a5d85',
    storageBucket: 'liveleak-a5d85.appspot.com',
    iosClientId: '30865018061-jipjtsfj93nnr5r983jci70nvqodkqlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveleak.RunnerTests',
  );
}
